### ISSUE TITLE
 Popcorn-Time-CE@0.4.0-2: npm start Does not launch 

### ISSUE THREAD

**Issue by codecakes** [PopcornTime-CE/desktop#104]
On my Ubuntu machine:

```
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:    16.04
Codename:   xenial
```

after doing a download of ver `0.4.0-2` which i extracted and which did not have a `gulpfile.js`(which I created copy pasted from the file on github), after following the installation process,Popcorn launched fine.

Then some notification came up and i dont remember what that was, but it had a restart button so i clicked on it.

After that nothing happened.

I did
`npm start` thrice nothing happend. 
also checked for running instances w/
`ps aux | grep npm`
yielded nothing suspicious there.

Doing a `rm -rf cache` on cache dir, followed by `npm start` did the trick.

FYI **UPDATE--**:
sreenshot here the notification comes again ![notification comes again](http://i.imgur.com/CZp74Rs.png)

Here is the output dump after doing `npm start` as and when its misbehaving:

```
npm start

> Popcorn-Time-CE@0.4.0-2 start /home/ubuntu/Downloads/popcorn
> gulp run

(node:15285) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:15285) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:15285) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[00:19:29] Using gulpfile ~/Downloads/popcorn/gulpfile.js
[00:19:29] Starting 'run'...
Using v0.12.3
Create cache folder in /home/ubuntu/Downloads/popcorn/cache/0.12.3
Using cache for: linux64
Launching App
```

**Comment by mauler** [comment]
https://github.com/PopcornTimeCommunity/desktop/pull/118

**Comment by YIFYtorrents** [comment]
You are not allowed to mix installation process because the github repo is not the same as the official release on github.

If you want download popcorn time for production then follow this steps:

#### Running
*Runs the app without building, useful for testing*

1. `git clone https://github.com/PopcornTime-CE/desktop.git`
1. `cd desktop`
1. `npm install`
1. `npm start`

#### Error

`The video could not be loaded, either because the server or network failed or because the format is not supported`

1. Go to your popcorntime directory `desktop` and paste/replace [libffmpegsumo.so](http://www33.zippyshare.com/v/4UZX7pu4/file.html) in it.

**Comment by captainyarr** [comment]
I haven't been able to get it to launch with the latest code either. I just get stuck on the Launching the app, and nothing after that.

**Comment by YIFYtorrents** [comment]
@captainyarr it is fixed now.

**Comment by captainyarr** [comment]
I am still having the same issue with the latest code as well.

**Comment by YIFYtorrents** [comment]
@captainyarr it works for me. so you are doing something wrong. check the latest comits

**Comment by captainyarr** [comment]
@YIFYtorrents 

Alright I was able to get it to start properly now. 

I did the following step:
1) Delete "Popcorn-Time-CE" folder in .config 
- Linux (~/.config/Popcorn-Time-CE)

**Comment by codecakes** [comment]
@YIFYtorrents

I suppose this is fixed now and can be closed?
